[package]
name = "hosted_vcs"
version = "0.0.1"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT"

[dependencies]
hyper = "0.6"
lazy_static = "0.1"
rustc-serialize = "0.3"
chrono = "0.2"

[dev-dependencies]
rpassword = "0.1"
