use super::user::User;

#[allow(dead_code)]
#[derive(Deserialize, Debug)]
pub struct Repository {
    id: u64,
    name: String,
    full_name: String,
    owner: User,
    private: bool,
    html_url: String,
    description: String,
    fork: bool,
    url: String,
    forks_url: String,
    keys_url: String,
    collaborators_url: String,
    teams_url: String,
    hooks_url: String,
    issue_events_url: String,
    events_url: String,
    assignees_url: String,
    branches_url: String,
    tags_url: String,
    blobs_url: String,
    git_tags_url: String,
    git_refs_url: String,
    trees_url: String,
    statuses_url: String,
    languages_url: String,
    stargazers_url: String,
    contributors_url: String,
    subscribers_url: String,
    subscription_url: String,
    commits_url: String,
    git_commits_url: String,
    comments_url: String,
    issue_comment_url: String,
    contents_url: String,
    compare_url: String,
    merges_url: String,
    archive_url: String,
    downloads_url: String,
    issues_url: String,
    pulls_url: String,
    milestones_url: String,
    notifications_url: String,
    labels_url: String,
    releases_url: String,
    created_at: String,
    updated_at: String,
    pushed_at: String,
    git_url: String,
    ssh_url: String,
    clone_url: String,
    svn_url: String,
    homepage: String,
    size: u32,
    stargazers_count: u32,
    watchers_count: u32,
    language: String,
    has_issues: bool,
    has_downloads: bool,
    has_wiki: bool,
    has_pages: bool,
    forks_count: u32,
    mirror_url: Option<String>,
    open_issues_count: u32,
    forks: u32,
    open_issues: u32,
    watchers: u32,
    default_branch: String,
    permissions: Option<RepositoryPermissions>,
    network_count: u32,
    subscribers_count: u32,
}

#[allow(dead_code)]
#[derive(Deserialize, Debug)]
pub struct RepositoryPermissions {
    admin: bool,
    push: bool,
    pull: bool,
}
